MVCForum.Website/Areas/Admin/ViewModels/AdminCategoryViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web;
using System.Web.Mvc;
using MVCForum.Domain.Constants;
using MVCForum.Domain.DomainModel;
using MVCForum.Website.Application;

namespace MVCForum.Website.Areas.Admin.ViewModels
{
    public class ListCategoriesViewModel
    {
        public IEnumerable<Category> Categories { get; set; }
    }

    public class CategoryViewModel
    {
        [HiddenInput]
        public Guid Id { get; set; }

        [DisplayName("Category Name")]
        [Required]
        [StringLength(600)]
        public string Name { get; set; }

        [DisplayName("Category Description")]
        [DataType(DataType.MultilineText)]
        [UIHint(AppConstants.EditorType), AllowHtml]
        public string Description { get; set; }

        [DisplayName("Category Colour")]
        [UIHint(AppConstants.EditorTemplateColourPicker), AllowHtml]
        public string CategoryColour { get; set; }

        [DisplayName("Lock The Category")]
        public bool IsLocked { get; set; }

        [DisplayName("Moderate all topics in this Category")]
        public bool ModerateTopics { get; set; }

        [DisplayName("Moderate all posts in this Category")]
        public bool ModeratePosts { get; set; }

        [DisplayName("Sort Order")]
        [Range(0, int.MaxValue)]
        public int SortOrder { get; set; }

        [DisplayName("Parent Category")]
        public Guid? ParentCategory { get; set; }

        public List<SelectListItem> AllCategories { get; set; }

        [DisplayName("Page Title")]
        [MaxLength(80)]
        public string PageTitle { get; set; }

        [DisplayName("Meta Desc")]
        [MaxLength(200)]
        public string MetaDesc { get; set; }

        [DisplayName("Category Image")]
        public HttpPostedFileBase[] Files { get; set; }
        public string Image { get; set; }
    }

    public class DeleteCategoryViewModel
    {
        [HiddenInput]
        public Guid Id { get; set; }
        public Category Category { get; set; }
        public List<Category> SubCategories { get; set; }
    }
}

MVCForum.Website/Areas/Admin/Controllers/AdminCategoryController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Hosting;
using System.Web.Mvc;
using MVCForum.Domain.Constants;
using MVCForum.Domain.DomainModel;
using MVCForum.Domain.Interfaces.Services;
using MVCForum.Domain.Interfaces.UnitOfWork;
using MVCForum.Website.Application;
using MVCForum.Website.Areas.Admin.ViewModels;

namespace MVCForum.Website.Areas.Admin.Controllers
{
    [Authorize(Roles = AppConstants.AdminRoleName)]
    public partial class AdminCategoryController : BaseAdminController
    {
        private readonly ICategoryService _categoryService;

        public AdminCategoryController(ILoggingService loggingService,
                                        IUnitOfWorkManager unitOfWorkManager,
                                       IMembershipService membershipService,
                                       ILocalizationService localizationService,
                                       ICategoryService categoryService,
                                       ISettingsService settingsService)
            : base(loggingService, unitOfWorkManager, membershipService, localizationService, settingsService)
        {
            _categoryService = categoryService;
        }

        public ActionResult Index()
        {
            return View();
        }

        [ChildActionOnly]
        public PartialViewResult GetMainCategories()
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var viewModel = new ListCategoriesViewModel
                                    {
                                        Categories = _categoryService.GetAll().OrderBy(x => x.SortOrder)
                                    };
                return PartialView(viewModel);
            }
        }

        public ActionResult CreateCategory()
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var categoryViewModel = new CategoryViewModel { AllCategories = _categoryService.GetBaseSelectListCategories(_categoryService.GetAll()) };
                return View(categoryViewModel);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCategory(CategoryViewModel categoryViewModel)
        {
            if (ModelState.IsValid)
            {
                using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
                {
                    try
                    {
                        var category = new Category
                                           {
                                               Name = categoryViewModel.Name,
                                               Description = categoryViewModel.Description,
                                               IsLocked = categoryViewModel.IsLocked,
                                               ModeratePosts = categoryViewModel.ModeratePosts,
                                               ModerateTopics = categoryViewModel.ModerateTopics,
                                               SortOrder = categoryViewModel.SortOrder,
                                               PageTitle = categoryViewModel.PageTitle,
                                               MetaDescription = categoryViewModel.MetaDesc,
                                               Colour = categoryViewModel.CategoryColour
                                           };

                        // Sort image out first
                        if (categoryViewModel.Files != null)
                        {
                            // Before we save anything, check the user already has an upload folder and if not create one
                            var uploadFolderPath = HostingEnvironment.MapPath(string.Concat(SiteConstants.Instance.UploadFolderPath, category.Id));
                            if (!Directory.Exists(uploadFolderPath))
                            {
                                Directory.CreateDirectory(uploadFolderPath);
                            }

                            // Loop through each file and get the file info and save to the users folder and Db
                            var file = categoryViewModel.Files[0];
                            if (file != null)
                            {
                                // If successful then upload the file
                                var uploadResult = AppHelpers.UploadFile(file, uploadFolderPath, LocalizationService, true);

                                if (!uploadResult.UploadSuccessful)
                                {
                                    TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                                    {
                                        Message = uploadResult.ErrorMessage,
                                        MessageType = GenericMessages.danger
                                    };
                                    return View(categoryViewModel);
                                }

                                // Save avatar to user
                                category.Image = uploadResult.UploadedFileName;
                            }

                        }

                        if (categoryViewModel.ParentCategory != null)
                        {
                            var parentCategory = _categoryService.Get(categoryViewModel.ParentCategory.Value);
                            category.ParentCategory = parentCategory;
                            SortPath(category, parentCategory);
                        }

                        _categoryService.Add(category);

                        // We use temp data because we are doing a redirect
                        TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                                                                        {
                                                                            Message = "Category Created",
                                                                            MessageType =
                                                                                GenericMessages.success
                                                                        };
                        unitOfWork.Commit();
                    }
                    catch (Exception)
                    {
                        unitOfWork.Rollback();
                    }
                }
            }
            else
            {
                ModelState.AddModelError("", "There was an error creating the category");
            }

            return RedirectToAction("Index");
        }


        private CategoryViewModel CreateEditCategoryViewModel(Category category)
        {
            var categoryViewModel = new CategoryViewModel
            {
                Name = category.Name,
                Description = category.Description,
                IsLocked = category.IsLocked,
                ModeratePosts = category.ModeratePosts == true,
                ModerateTopics = category.ModerateTopics == true,
                SortOrder = category.SortOrder,
                Id = category.Id,
                PageTitle = category.PageTitle,
                MetaDesc = category.MetaDescription,
                Image = category.Image,
                CategoryColour = category.Colour,
                ParentCategory = category.ParentCategory == null ? Guid.Empty : category.ParentCategory.Id,
                AllCategories = _categoryService.GetBaseSelectListCategories(_categoryService.GetAll()
                    .Where(x => x.Id != category.Id)
                    .ToList())
            };
            return categoryViewModel;
        }

        public ActionResult EditCategory(Guid id)
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var category = _categoryService.Get(id);
                var categoryViewModel = CreateEditCategoryViewModel(category);

                return View(categoryViewModel);
            }
        }

        [HttpPost]
        public ActionResult EditCategory(CategoryViewModel categoryViewModel)
        {
            if (ModelState.IsValid)
            {
                using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
                {
                    try
                    {

                        var category = _categoryService.Get(categoryViewModel.Id);
                        var parentCat = categoryViewModel.ParentCategory != null
                                            ? _categoryService.Get((Guid)categoryViewModel.ParentCategory.Value)
                                            : null;

                        // Check they are not trying to add a subcategory of this category as the parent or it will break
                        if (parentCat?.Path != null && categoryViewModel.ParentCategory != null)
                        {
                            var parentCats = parentCat.Path.Split(',').Where(x => !string.IsNullOrEmpty(x)).Select(x => new Guid(x)).ToList();
                            if (parentCats.Contains(categoryViewModel.Id))
                            {
                                // Remove the parent category, but still let them create the catgory
                                categoryViewModel.ParentCategory = null;
                            }
                        }

                        // Sort image out first
                        if (categoryViewModel.Files != null)
                        {
                            // Before we save anything, check the user already has an upload folder and if not create one
                            var uploadFolderPath = HostingEnvironment.MapPath(string.Concat(SiteConstants.Instance.UploadFolderPath, categoryViewModel.Id));
                            if (!Directory.Exists(uploadFolderPath))
                            {

MVCForum.Website/Areas/Admin/Views/AdminCategory/CreateCategory.cshtml
@model MVCForum.Website.Areas.Admin.ViewModels.CategoryViewModel
@{
    ViewBag.Title = "Create Category";
}

@Html.Partial("_CategoryNavButtons")

<div class="panel">
    <div class="panel-heading">
        <h5>@ViewBag.Title</h5>
    </div>
    <div class="panel-content">
        @using (Html.BeginForm("CreateCategory", "AdminCategory", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.ValidationSummary(false)
            @Html.AntiForgeryToken()

            @Html.Partial("_CategoryFields", Model)

            <div class="submit-holder">
                <input type="submit" class="btn-mvc-green btn-mvc-large" value="Create" />
            </div>
        }
    </div>
</div>

MVCForum.Website/Areas/Admin/Views/AdminCategory/DeleteCategoryConfirmation.cshtml
@model MVCForum.Website.Areas.Admin.ViewModels.DeleteCategoryViewModel
@{
    ViewBag.Title = "Delete Category";
    var topicCount = Model.Category.Topics.Count;
}

@Html.Partial("_CategoryNavButtons")

<div class="panel">
    <div class="panel-heading">
        <h5>@ViewBag.Title</h5>
    </div>
    <div class="panel-content">
        @if (Model.SubCategories.Any())
        {
            <h2>Unable To Delete</h2>
            <p>This category has sub categories, please re-assign them to new parent categories first</p>

            <h4>Sub Categories</h4>
            <ul>
                @foreach (var subCat in Model.SubCategories)
                {
                    <li><strong>@subCat.Name</strong></li>
                }
            </ul>

            <a href="@Url.Action("Index")" class="btn-mvc btn-mvc-large">Back</a>
        }
        else if (Model.Category.Topics.Any())
        {
            <h2>Unable To Delete</h2>
            <p>This category has discussions associated with it, please either delete or move the topics to a different category</p>

            <h4>Topics</h4>
            <ul>
                @foreach (var topic in Model.Category.Topics.Take(10))
                {
                    <li><a href="@topic.NiceUrl">@topic.Name</a></li>
                }
            </ul>
            if (topicCount > 10)
            {
                <p>And @(topicCount - 10) other topics...</p>
            }
            <a href="@Url.Action("Index")" class="btn-mvc btn-mvc-large">Back</a>
        }
        else
        {
            using (Html.BeginForm("DeleteCategory", "AdminCategory", FormMethod.Post))
            {
                <h2>Delete Category?</h2>
                <p>Are you sure you want to delete this Category? You cannot undo this action.</p>
                @Html.HiddenFor(x => x.Id)
                <div class="submit-holder">
                    <input type="submit" class="btn-mvc btn-mvc-large" value="Yes" />
                </div>
            }
        }
    </div>
</div>

MVCForum.Website/Areas/Admin/Views/AdminCategory/EditCategory.cshtml
@model MVCForum.Website.Areas.Admin.ViewModels.CategoryViewModel

@{
    ViewBag.Title = "Edit Category";
}

@Html.Partial("_CategoryNavButtons")

<div class="panel">
    <div class="panel-heading">
        <h5>@ViewBag.Title</h5>
    </div>
    <div class="panel-content">
        @using (Html.BeginForm("EditCategory", "AdminCategory", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.ValidationSummary(false)
            @Html.HiddenFor(model => model.Id)

            @Html.Partial("_CategoryFields", Model)

            <div class="submit-holder">
                <input type="submit" class="btn-mvc-green btn-mvc-large" value="Update" />
                <a href="@Url.Action("DeleteCategoryConfirmation", new { id = Model.Id })" class="btn-mvc btn-mvc-large" role="button">Delete</a>
            </div>
        }

    </div>
</div>

MVCForum.Website/Areas/Admin/Views/AdminCategory/GetMainCategories.cshtml
@using MVCForum.Domain.DomainModel
@model MVCForum.Website.Areas.Admin.ViewModels.ListCategoriesViewModel
@{
    var mainCategories = Model.Categories.Where(x => x.ParentCategory == null).ToList();
}

<div class="panel">
    <div class="panel-heading">
        <h5>All Categories</h5>
    </div>
    <div class="panel-content">
        <div id="container">
            <ul>
                @foreach (var cat in mainCategories)
                {
                    <li class="maincategory">
                        <a href="@Url.Action("EditCategory", new { id = cat.Id })">
                            @Html.Raw(cat.Name)
                        </a>
                        @GetSubCategories(cat)
                    </li>
                }

            </ul>
        </div>
    </div>
</div>



@helper GetSubCategories(Category cat)
{
    var subCategories = Model.Categories.Where(x => x.ParentCategory != null && x.ParentCategory.Id == cat.Id).ToList();
    if (subCategories.Any())
    {
        <ul>
            @foreach (var subCat in subCategories)
            {
                <li>
                    <a href="@Url.Action("EditCategory", new { id = subCat.Id })">
                        @Html.Raw(subCat.Name)
                    </a>
                    @GetSubCategories(subCat)
                </li>
            }
        </ul>
    }
}

MVCForum.Website/Areas/Admin/Views/AdminCategory/Index.cshtml
@{
    ViewBag.Title = "Manage Categories";
}

@section AdminHeader
{
    <link href="@Url.Content("~/Content/jstree/themes/proton/style.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Content/jstree/jstree.min.js")"></script>
    <script>
        $(function () {
            $('#container').jstree({
                'core': {
                    'themes': {
                        'name': 'proton',
                        'responsive': true
                    },
                    'check_callback': true
                }
            }).bind("select_node.jstree", function (e, data) {
                var href = data.node.a_attr.href;
                document.location.href = href;
            });
            //,
            //'plugins': ["dnd"]
            //$(document).on('dnd_start.vakata', function (e, data) {
            //    console.log('Started');
            //});
            //$(document).on('dnd_stop.vakata', function (e, data) {
            //    var eValue = e;
            //    var dataValue = data;
            //});
        });
    </script>

}

@Html.Partial("_CategoryNavButtons")


@Html.Action("GetMainCategories")

MVCForum.Website/Areas/Admin/Views/AdminCategory/_CategoryFields.cshtml
@using MVCForum.Website.Application.ExtensionMethods
@model MVCForum.Website.Areas.Admin.ViewModels.CategoryViewModel

<div class="form-group">
    @Html.LabelFor(model => model.CategoryColour)
    @Html.EditorFor(model => model.CategoryColour)
    @Html.ValidationMessageFor(model => model.CategoryColour)
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
    @Html.ValidationMessageFor(model => model.Name)
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Description)
    @Html.EditorFor(model => model.Description)
    @Html.ValidationMessageFor(model => model.Description)
</div>

<div class="row categoryimage">

    @if (!string.IsNullOrEmpty(Model.Image))
    {
        <div class="col-md-2">
            <img src="@AppHelpers.CategoryImage(Model.Image, Model.Id,110)" alt="@Model.Name" />
        </div>
    }

    <div class="col-md-10">
        @Html.LabelFor(x => x.Files)
        <div class="input-group">
            <span class="input-group-btn">
                <span class="btn btn-default btn-file">
                    @Html.LanguageString("Post.Browse") <input type="file" name="files" id="files" value="">
                </span>
            </span>
            <input type="text" class="form-control" readonly="">
        </div>
        @Html.ValidationMessageFor(x => x.Files)
    </div>
</div>

<div class="checkbox">
    @using (Html.BeginLabelFor(m => m.IsLocked, new { @class = "checkbox" }))
    {
        @Html.CheckBoxFor(m => m.IsLocked)
    }
    @Html.ValidationMessageFor(m => m.IsLocked)
</div>

<div class="checkbox">
    @using (Html.BeginLabelFor(m => m.ModerateTopics, new { @class = "checkbox" }))
    {
        @Html.CheckBoxFor(m => m.ModerateTopics)
    }
    @Html.ValidationMessageFor(m => m.ModerateTopics)
</div>

<div class="checkbox">
    @using (Html.BeginLabelFor(m => m.ModeratePosts, new { @class = "checkbox" }))
    {
        @Html.CheckBoxFor(m => m.ModeratePosts)
    }
    @Html.ValidationMessageFor(m => m.ModeratePosts)
</div>

<div class="form-group">
    @Html.LabelFor(model => model.SortOrder)
    @Html.TextBoxFor(model => model.SortOrder, new { @class = "form-control", type = "number" })
    @Html.ValidationMessageFor(model => model.SortOrder)
</div>

<div class="form-group">
    @Html.LabelFor(model => model.ParentCategory)
    @Html.DropDownListFor(model => model.ParentCategory, Model.AllCategories, new { @class = "form-control" })
    @Html.ValidationMessageFor(model => model.ParentCategory)
</div>

<hr />

<div class="form-group">
    @Html.LabelFor(model => model.PageTitle)
    @Html.TextBoxFor(model => model.PageTitle, new { @class = "form-control" })
    @Html.ValidationMessageFor(model => model.PageTitle)
</div>

<div class="form-group">
    @Html.LabelFor(model => model.MetaDesc)
    @Html.TextAreaFor(model => model.MetaDesc, new { @class = "form-control" })
    @Html.ValidationMessageFor(model => model.MetaDesc)
</div>

MVCForum.Website/Areas/Admin/Views/AdminCategory/_CategoryNavButtons.cshtml
<div class="topadminsubnav">
    <div class="btn-group" role="group">
        <a href="@Url.Action("Index")" role="button" class="btn-mvc-green">Manage Categories</a>
        <a href="@Url.Action("CreateCategory")" role="button" class="btn-mvc-green">Create New</a>
    </div>
</div>