MVCForum.Website/Areas/Admin/ViewModels/BannedWordViewModels.cs
using System;
using System.ComponentModel.DataAnnotations;
using MVCForum.Domain.DomainModel;

namespace MVCForum.Website.Areas.Admin.ViewModels
{
    public class BannedWordListViewModel
    {
        public PagedList<BannedWord> Words { get; set; }

        public int? PageIndex { get; set; }
        public int? TotalCount { get; set; }
        public string Search { get; set; }
    }

    public class AddBannedWordViewModel
    {
        [Required]
        public string Word { get; set; }
        public bool IsStopWord { get; set; }
    }

    public class AjaxEditWordViewModel
    {
        [Required]
        public Guid WordId { get; set; }

        [Required]
        public string NewName { get; set; }
    }
}

MVCForum.Website/Areas/Admin/Controllers/BannedWordController.cs
using System;
using System.Web.Mvc;
using MVCForum.Domain.Constants;
using MVCForum.Domain.DomainModel;
using MVCForum.Domain.Interfaces.Services;
using MVCForum.Domain.Interfaces.UnitOfWork;
using MVCForum.Website.Application;
using MVCForum.Website.Areas.Admin.ViewModels;

namespace MVCForum.Website.Areas.Admin.Controllers
{
    [Authorize(Roles = AppConstants.AdminRoleName)]
    public partial class BannedWordController : BaseAdminController
    {

        private readonly IBannedWordService _bannedWordService;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="unitOfWorkManager"> </param>
        /// <param name="membershipService"></param>
        /// <param name="localizationService"> </param>
        /// <param name="settingsService"> </param>
        /// <param name="loggingService"> </param>
        /// <param name="bannedWordService"></param>
        public BannedWordController(ILoggingService loggingService,
            IUnitOfWorkManager unitOfWorkManager,
            IMembershipService membershipService,
            ILocalizationService localizationService,
            ISettingsService settingsService, 
            IBannedWordService bannedWordService)
            : base(loggingService, unitOfWorkManager, membershipService, localizationService, settingsService)
        {
            _bannedWordService = bannedWordService;
        }


        public ActionResult Index(int? p, string search)
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var pageIndex = p ?? 1;
                var allEmails = string.IsNullOrEmpty(search) ? _bannedWordService.GetAllPaged(pageIndex, SiteConstants.Instance.AdminListPageSize) :
                                    _bannedWordService.GetAllPaged(search, pageIndex, SiteConstants.Instance.AdminListPageSize);

                var viewModel = new BannedWordListViewModel
                    {
                        Words = allEmails,
                        PageIndex = pageIndex,
                        TotalCount = allEmails.TotalCount,
                        Search = search
                    };
                
                return View(viewModel);
            }
            
        }

        [HttpPost]
        public ActionResult Add(AddBannedWordViewModel addBannedEmailViewModel)
        {
            using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
            {
                try
                {
                    if (!string.IsNullOrEmpty(addBannedEmailViewModel.Word))
                    {
                        var bannedWord = new BannedWord
                        {
                            Word = addBannedEmailViewModel.Word,
                            DateAdded = DateTime.UtcNow,
                            IsStopWord = addBannedEmailViewModel.IsStopWord
                        };

                        _bannedWordService.Add(bannedWord);

                        TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                        {
                            Message = "Word added",
                            MessageType = GenericMessages.success
                        };

                        unitOfWork.Commit();
                    }
                    else
                    {
                        TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                        {
                            Message = "Please add a word",
                            MessageType = GenericMessages.danger
                        };
                    }

                }
                catch (Exception ex)
                {
                    unitOfWork.Rollback();
                    LoggingService.Error(ex);
                    TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                    {
                        Message = LocalizationService.GetResourceString("Errors.GenericMessage"),
                        MessageType = GenericMessages.danger
                    }; 
                }
            }

            return RedirectToAction("Index");
        }

        public ActionResult Delete(Guid id, int? p, string search)
        {
            using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
            {
                try
                {
                    var word = _bannedWordService.Get(id);
                    if (word == null)
                    {
                        throw new ApplicationException("Cannot delete word - Word does not exist");
                    }

                    _bannedWordService.Delete(word);

                    ViewBag.Message = new GenericMessageViewModel
                    {
                        Message = "Word delete successfully",
                        MessageType = GenericMessages.success
                    };
                    unitOfWork.Commit();
                }
                catch (Exception ex)
                {
                    unitOfWork.Rollback();
                    LoggingService.Error(ex);
                    ViewBag.Message = new GenericMessageViewModel
                    {
                        Message = string.Format("Delete failed: {0}", ex.Message),
                        MessageType = GenericMessages.danger
                    };
                }

                return RedirectToAction("Index", new { p, search });
            }
        }

        /// <summary>
        /// Edit a resource key
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public void AjaxUpdateWord(AjaxEditWordViewModel viewModel)
        {
            if (Request.IsAjaxRequest())
            {
                using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
                {
                    try
                    {
                        var wordToUpdate = _bannedWordService.Get(viewModel.WordId);
                        wordToUpdate.Word = viewModel.NewName;
                        unitOfWork.Commit();
                    }
                    catch (Exception ex)
                    {
                        unitOfWork.Rollback();
                        LoggingService.Error(ex);
                    }
                }
            }
        }
    }
}

MVCForum.Website/Areas/Admin/Views/BannedWord/Index.cshtml
@using MVCForum.Domain.Constants
@model MVCForum.Website.Areas.Admin.ViewModels.BannedWordListViewModel
@{
    ViewBag.Title = "Banned & Stop Words";
}

<div class="panel">
    <div class="panel-heading">
        <h5>@ViewBag.Title</h5>
    </div>
    <div class="panel-content">
        <div class="row">
            <div class="col-md-5">
                @using (Html.BeginForm("Index", "BannedWord", FormMethod.Get))
                {
                    <div class="input-group tablesearch">
                        @Html.TextBoxFor(x => Model.Search, new { @class = "form-control" })
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">Search</button>
                        </span>
                    </div>
                    @Html.Hidden("p", Model.PageIndex)
                }
            </div>
            <div class="col-md-7">
                @using (Html.BeginForm("Add", "BannedWord", FormMethod.Post, new { @class = "form-inline" }))
                {
                    <div class="form-group">
                        <label class="sr-only" for="Word">Word</label>
                        @Html.TextBox("Word", null, new { @class = "form-control" })
                    </div>
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="IsStopWord" id="IsStopWord" value="true"> Is Stop Word?
                            <input type="hidden" value="false" name="IsStopWord" />
                        </label>
                    </div>
                    <button type="submit" class="btn btn-default">Add</button>
                }
            </div>
        </div>

        @if (Model.TotalCount > 0)
        {
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th style="width: 65px;">Edit</th>
                        <th>Word</th>
                        <th style="width: 120px;">Is Stop Word</th>
                        <th style="width: 65px;">Delete</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var word in Model.Words)
                    {
                        <tr>
                            <td>
                                <span class="editbannedword">
                                    <a href="#" class="btn-mvc">
                                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                    </a>
                                </span>
                                <span class="savebannedword" style="display: none;">
                                    <a href="#" class="btn-mvc">
                                        <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                                    </a>
                                </span>
                            </td>
                            <td class="bannedwordvalue">
                                <span class="bannedwordvaluedisplay">
                                    @Html.Raw(word.Word)
                                </span>
                                <span class="bannedwordvalueedit" style="display: none;">
                                    <input data-wordid="@word.Id" data-oldvalue="@word.Word" type="text" id="@word.Id" value="@word.Word" class="bannedwordinput form-control" />
                                </span>
                            </td>
                            <td>
                                <input type="checkbox" @(word.IsStopWord == true ? "checked=\"checked\"" : "") disabled="disabled" />
                            </td>
                            <td>
                                <a href="@Url.Action("Delete", new { word.Id, p = Model.PageIndex, search = Model.Search })" class="btn-mvc">
                                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                </a>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>

            if (Model.Words.TotalPages > 1)
            {
                @Html.Pager(Convert.ToInt32(Model.PageIndex), SiteConstants.Instance.AdminListPageSize, Convert.ToInt32(Model.TotalCount), new { search = Model.Search })
            }
        }



    </div>
</div>

<div class="panel">
    <div class="panel-heading">
        <h5>Description</h5>
    </div>
    <div class="panel-content">
        <p><strong>Banned words!</strong> Are words that are matched and are replaced with a charactor that you can define in a web.config app setting called BannedWordReplaceCharactor</p>
        <p>By default its set to '?' (i.e. if you had <strong>feck</strong> in the list, it would become <strong>????</strong>). You can add a single word, or you can add wildcards at the end of your word.</p>
        <p>For example, if you wanted to ban feck, fecking, feckers etc... You can add <strong>feck*</strong> which will match feck AND anything after.</p>
        <p><strong>Stop Words!</strong> If you select a word to be a stop word. Then instead of replacing charactors is just abandons the current action. So for example you could put a stop word as sex.com which would stop link spammers.</p>
        <p>Or you could just use normal words like Viagra, which would stop anyone trying to post with that in (This also applies to profiles, so they can't sign up just to get a link).</p>
    </div>
</div>