MVCForum.Website/ViewModels/SearchViewModels.cs
using System.Collections.Generic;

namespace MVCForum.Website.ViewModels
{
    public class SearchViewModel
    {
        public List<PostViewModel> Posts { get; set; }
        public int? PageIndex { get; set; }
        public int? TotalCount { get; set; }
        public int? TotalPages { get; set; }
        public string Term { get; set; }

    }
}

MVCForum.Website/Controllers/MembersController.cs
namespace MVCForum.Website.Controllers
{
    using System;
    using System.Drawing.Imaging;
    using System.IO;
    using System.Linq;
    using System.Security.Principal;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web;
    using System.Web.Hosting;
    using System.Web.Mvc;
    using System.Web.Security;
    using Domain.Constants;
    using Domain.DomainModel;
    using Domain.DomainModel.Enums;
    using Domain.Events;
    using Domain.Interfaces.Services;
    using Domain.Interfaces.UnitOfWork;
    using Utilities;
    using Application;
    using Areas.Admin.ViewModels;
    using ViewModels;
    using ViewModels.Mapping;
    using MembershipCreateStatus = Domain.DomainModel.MembershipCreateStatus;
    using MembershipUser = Domain.DomainModel.MembershipUser;

    public partial class MembersController : BaseController
    {
        private readonly IPostService _postService;
        private readonly ITopicService _topicService;
        private readonly IReportService _reportService;
        private readonly IEmailService _emailService;
        private readonly IPrivateMessageService _privateMessageService;
        private readonly IBannedEmailService _bannedEmailService;
        private readonly IBannedWordService _bannedWordService;
        private readonly ICategoryService _categoryService;

        public MembersController(ILoggingService loggingService, IUnitOfWorkManager unitOfWorkManager, IMembershipService membershipService, ILocalizationService localizationService,
            IRoleService roleService, ISettingsService settingsService, IPostService postService, IReportService reportService, 
            IEmailService emailService, IPrivateMessageService privateMessageService, IBannedEmailService bannedEmailService, 
            IBannedWordService bannedWordService, ICategoryService categoryService, ITopicService topicService, ICacheService cacheService)
            : base(loggingService, unitOfWorkManager, membershipService, localizationService, roleService, settingsService, cacheService)
        {
            _postService = postService;
            _reportService = reportService;
            _emailService = emailService;
            _privateMessageService = privateMessageService;
            _bannedEmailService = bannedEmailService;
            _bannedWordService = bannedWordService;
            _categoryService = categoryService;
            _topicService = topicService;
        }

        [Authorize(Roles = AppConstants.AdminRoleName)]
        public ActionResult SrubAndBanUser(Guid id)
        {
            var user = MembershipService.GetUser(id);

            using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
            {
                if (!user.Roles.Any(x => x.RoleName.Contains(AppConstants.AdminRoleName)))
                {
                    MembershipService.ScrubUsers(user, unitOfWork);

                    try
                    {
                        unitOfWork.Commit();
                        TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                        {
                            Message = LocalizationService.GetResourceString("Members.SuccessfulSrub"),
                            MessageType = GenericMessages.success
                        };
                    }
                    catch (Exception ex)
                    {
                        unitOfWork.Rollback();
                        LoggingService.Error(ex);
                        TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                        {
                            Message = LocalizationService.GetResourceString("Members.UnSuccessfulSrub"),
                            MessageType = GenericMessages.danger
                        };
                    }
                }
            }

            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var viewModel = ViewModelMapping.UserToMemberEditViewModel(user);
                viewModel.AllRoles = RoleService.AllRoles();
                return Redirect(user.NiceUrl);
            }

        }

        [Authorize]
        public ActionResult BanMember(Guid id)
        {
            using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
            {
                var user = MembershipService.GetUser(id);
                var permissions = RoleService.GetPermissions(null, UsersRole);

                if (permissions[SiteConstants.Instance.PermissionEditMembers].IsTicked)
                {

                    if (!user.Roles.Any(x => x.RoleName.Contains(AppConstants.AdminRoleName)))
                    {
                        user.IsBanned = true;

                        try
                        {
                            unitOfWork.Commit();
                            TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                            {
                                Message = LocalizationService.GetResourceString("Members.NowBanned"),
                                MessageType = GenericMessages.success
                            };
                        }
                        catch (Exception ex)
                        {
                            unitOfWork.Rollback();
                            LoggingService.Error(ex);
                            TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                            {
                                Message = LocalizationService.GetResourceString("Error.UnableToBanMember"),
                                MessageType = GenericMessages.danger
                            };
                        }
                    }
                }

                return Redirect(user.NiceUrl);
            }
        }

        [Authorize]
        public ActionResult UnBanMember(Guid id)
        {
            using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
            {
                var user = MembershipService.GetUser(id);
                var permissions = RoleService.GetPermissions(null, UsersRole);

                if (permissions[SiteConstants.Instance.PermissionEditMembers].IsTicked)
                {
                    if (!user.Roles.Any(x => x.RoleName.Contains(AppConstants.AdminRoleName)))
                    {
                        user.IsBanned = false;

                        try
                        {
                            unitOfWork.Commit();
                            TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                            {
                                Message = LocalizationService.GetResourceString("Members.NowUnBanned"),
                                MessageType = GenericMessages.success
                            };
                        }
                        catch (Exception ex)
                        {
                            unitOfWork.Rollback();
                            LoggingService.Error(ex);
                            TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                            {
                                Message = LocalizationService.GetResourceString("Error.UnableToUnBanMember"),
                                MessageType = GenericMessages.danger
                            };
                        }
                    }
                }

                return Redirect(user.NiceUrl);
            }
        }


        [ChildActionOnly]
        public PartialViewResult GetCurrentActiveMembers()
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var viewModel = new ActiveMembersViewModel
                {
                    ActiveMembers = MembershipService.GetActiveMembers()
                };
                return PartialView(viewModel);
            }
        }

        public JsonResult LastActiveCheck()
        {
            if (UserIsAuthenticated)
            {
                var rightNow = DateTime.UtcNow;
                var usersDate = LoggedOnReadOnlyUser.LastActivityDate ?? DateTime.UtcNow.AddDays(-1);

                var span = rightNow.Subtract(usersDate);
                var totalMins = span.TotalMinutes;

                if (totalMins > AppConstants.TimeSpanInMinutesToDoCheck)
                {
                    using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
                    {
                        // Actually get the user, LoggedOnUser has no tracking
                        var loggedOnUser = MembershipService.GetUser(Username);

                        // Update users last activity date so we can show the latest users online
                        loggedOnUser.LastActivityDate = DateTime.UtcNow;

                        // Update
                        try
                        {
                            unitOfWork.Commit();
                        }
                        catch (Exception ex)
                        {
                            unitOfWork.Rollback();
                            LoggingService.Error(ex);
                        }
                    }
                }
            }

            // You can return anything to reset the timer.
            return Json(new { Timer = "reset" }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetByName(string slug)
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var member = MembershipService.GetUserBySlug(slug);
                var loggedonId = UserIsAuthenticated ? LoggedOnReadOnlyUser.Id : Guid.Empty;
                var permissions = RoleService.GetPermissions(null, UsersRole);

                // Localise the badge names
                foreach (var item in member.Badges)
                {
                    var partialKey = string.Concat("Badge.", item.Name);

MVCForum.Website/Controllers/SearchController.cs
namespace MVCForum.Website.Controllers
{
    using System.Linq;
    using System.Web.Mvc;
    using Domain.Constants;
    using Domain.Interfaces.Services;
    using Domain.Interfaces.UnitOfWork;
    using ViewModels;
    using ViewModels.Mapping;

    public partial class SearchController : BaseController
    {
        private readonly IPostService _postService;
        private readonly ICategoryService _categoryService;
        private readonly IVoteService _voteService;
        private readonly IFavouriteService _favouriteService;

        public SearchController(ILoggingService loggingService, IUnitOfWorkManager unitOfWorkManager,
            IMembershipService membershipService, ILocalizationService localizationService,
            IRoleService roleService, ISettingsService settingsService,
            IPostService postService, IVoteService voteService, IFavouriteService favouriteService, 
            ICategoryService categoryService, ICacheService cacheService)
            : base(loggingService, unitOfWorkManager, membershipService, localizationService, roleService, settingsService, cacheService)
        {
            _postService = postService;
            _voteService = voteService;
            _favouriteService = favouriteService;
            _categoryService = categoryService;
        }

        [HttpGet]
        public ActionResult Index(int? p, string term)
        {
            if (!string.IsNullOrEmpty(term))
            {
                using (UnitOfWorkManager.NewUnitOfWork())
                {
                    if (!string.IsNullOrEmpty(term))
                    {
                        term = term.Trim();
                    }

                    // Get the global settings
                    var settings = SettingsService.GetSettings();

                    // Get allowed categories
                    var allowedCategories = _categoryService.GetAllowedCategories(UsersRole);


                    // Set the page index
                    var pageIndex = p ?? 1;

                    // Get all the topics based on the search value
                    var posts = _postService.SearchPosts(pageIndex,
                                                         SiteConstants.Instance.SearchListSize,
                                                         int.MaxValue,
                                                         term,
                                                         allowedCategories);

                    // Get all the permissions for these topics
                    var topicPermissions = ViewModelMapping.GetPermissionsForTopics(posts.Select(x => x.Topic), RoleService, UsersRole);

                    // Get the post Ids
                    var postIds = posts.Select(x => x.Id).ToList();

                    // Get all votes for these posts
                    var votes = _voteService.GetVotesByPosts(postIds);

                    // Get all favourites for these posts
                    var favs = _favouriteService.GetAllPostFavourites(postIds);

                    // Create the post view models
                    var viewModels = ViewModelMapping.CreatePostViewModels(posts.ToList(), votes, topicPermissions, LoggedOnReadOnlyUser, settings, favs);

                    // create the view model
                    var viewModel = new SearchViewModel
                    {
                        Posts = viewModels,
                        PageIndex = pageIndex,
                        TotalCount = posts.TotalCount,
                        TotalPages = posts.TotalPages,
                        Term = term
                    };

                    return View(viewModel);
                }
            }

            return RedirectToAction("Index", "Home");
        }


        [ChildActionOnly]
        public PartialViewResult SideSearch()
        {
            return PartialView();
        }

    }
}

MVCForum.Website/Views/Members/AdminMemberProfileTools.cshtml
@using MVCForum.Domain.Constants
@model MVCForum.Website.ViewModels.ViewMemberViewModel
<div class="adminprofiletools">
    
    @if(!Model.User.IsBanned)
    {
        <p><a href="@Url.Action("BanMember", "Members", new {id = Model.User.Id }, null)" class="btn-mvc">@Html.LanguageString("Members.BanUser")</a></p>
    }
    else
    {
        <p><a href="@Url.Action("UnBanMember", "Members", new {id = Model.User.Id }, null)" class="btn-mvc">@Html.LanguageString("Members.UnBanUser")</a></p>
    }

    <p><a href="@Url.Action("Edit", "Members", new { Model.User.Id }, null)" class="btn-mvc">@Html.LanguageString("Members.EditMember")</a></p>      

    @if (User.IsInRole(AppConstants.AdminRoleName))
    {
        <p><a href="@Url.Action("SrubAndBanUser", "Members", new { id = Model.User.Id }, null)" class="btn-mvc" onclick="return confirm('@Html.LanguageString("Confirmation.SrubAndBan")')">@Html.LanguageString("Members.SrubAndBan")</a></p> 
    }

</div>

MVCForum.Website/Views/Members/ChangePassword.cshtml
@model MVCForum.Website.ViewModels.ChangePasswordViewModel

@{
    Layout = "~/Views/Shared/_LayoutFullWidth.cshtml";
    ViewBag.Title = Html.LanguageString("Members.ChangePassword.Title");
}

<div class="row">

    <div class="col-md-6 col-md-offset-3">
        @using (Html.BeginForm("ChangePassword", "Members", FormMethod.Post, new { @class = "form-forgotpassword" }))
        {
            @Html.ValidationSummary(true)
            @Html.AntiForgeryToken()

            <fieldset>
                <legend>@ViewBag.Title</legend>

                <p>
                    @string.Format(Html.LanguageString("Members.ChangePassword.Text"), Membership.MinRequiredPasswordLength)
                </p>

                <div class="form-group">
                    @Html.LabelFor(m => m.OldPassword)
                    @Html.PasswordFor(m => m.OldPassword, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.OldPassword)
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.NewPassword)
                    @Html.PasswordFor(m => m.NewPassword, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.NewPassword)
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.ConfirmPassword)
                    @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.ConfirmPassword)
                </div>

                <div class="submit-holder">
                    <button type="submit" class="btn-mvc-green btn-mvc-large">@Html.LanguageString("Buttons.ChangePassword")</button>
                </div>
            </fieldset>

        }
    </div>
</div>

MVCForum.Website/Views/Members/Edit.cshtml
@using MVCForum.Website.Application.ExtensionMethods
@model MVCForum.Website.ViewModels.MemberFrontEndEditViewModel

@{
    Layout = "~/Views/Shared/_LayoutFullWidth.cshtml";
    ViewBag.Title = Html.LanguageString("Members.EditProfile");
    var settings = Html.Settings();
}
@section Header
{
    <script type="text/javascript">
        $.ajax({
            url: app_base + 'Badge/ProfileBadgeCheck',
            type: 'POST',
            error: function (xhr, ajaxOptions, thrownError) {
                ShowUserMessage("Error: " + xhr.status + " " + thrownError);
            }
        });
    </script>

}
<div class="row">

    <div class="col-md-6 col-md-offset-3">
        @using (Html.BeginForm("Edit", "Members", FormMethod.Post, new { enctype = "multipart/form-data", @class = "editmemberform" }))
        {
            @Html.HiddenFor(x => Model.Id)

            @Html.ValidationSummary(true)

            <fieldset>
                <legend>@ViewBag.Title</legend>

                <p class="changepasswordtext">
                    @Html.Raw(string.Format(Html.LanguageString("Members.ChangePassword.Link"), string.Format("<a href=\"{0}\">{1}</a>", Url.Action("ChangePassword"), Html.LanguageString("Members.ChangePassword.Title"))))
                </p>

                <div class="form-group">
                    @Html.LabelFor(x => x.UserName)
                    @Html.TextBoxFor(x => x.UserName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.UserName)
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.Email)
                    @Html.TextBoxFor(x => x.Email, new { @class = "form-control", type = "email" })
                    @Html.ValidationMessageFor(x => x.Email)
                </div>

                @if (!Model.DisableFileUploads)
                {
                    <div class="row membereditavatar">
                        <div class="col-md-2">
                            <img src="@AppHelpers.MemberImage(Model.Avatar, Model.Email, Model.Id, SiteConstants.Instance.GravatarProfileSize)" alt="@Model.UserName">
                        </div>
                        <div class="col-md-10">
                            @Html.LabelFor(x => x.Files)
                            <div class="input-group">
                                <span class="input-group-btn">
                                    <span class="btn btn-default btn-file">
                                        @Html.LanguageString("Post.Browse") <input type="file" name="files" id="files" value="">
                                    </span>
                                </span>
                                <input type="text" class="form-control" readonly="">
                            </div>
                            @Html.ValidationMessageFor(x => x.Files)
                        </div>
                    </div>
                }

                <div class="form-group">
                    @Html.LabelFor(x => x.Age)
                    @Html.TextBoxFor(x => x.Age, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Age)
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.Location)
                    @Html.TextBoxFor(x => x.Location, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Location)
                </div>

                @if (Model.AmountOfPoints >= settings.PointsAllowedForExtendedProfile)
                {
                    <div class="form-group">
                        @Html.LabelFor(x => x.Website)
                        @Html.TextBoxFor(x => x.Website, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Website)
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(x => x.Twitter)
                        @Html.TextBoxFor(x => x.Twitter, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Twitter)
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(x => x.Facebook)
                        @Html.TextBoxFor(x => x.Facebook, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Facebook)
                    </div>

                    if (settings.EnableSignatures)
                    {
                        <div class="form-group">
                            @Html.LabelFor(x => x.Signature)
                            @Html.TextAreaFor(x => x.Signature, new { @class = "form-control" })
                            @Html.ValidationMessageFor(x => x.Signature)
                        </div>
                    }
                }

                <div class="checkbox">
                    @using (Html.BeginLabelFor(m => m.DisableEmailNotifications, new {@class = "checkbox"}))
                    {
                        @Html.CheckBoxFor(m => m.DisableEmailNotifications)
                    }
                    @Html.ValidationMessageFor(m => m.DisableEmailNotifications)
                </div>

                <div class="submit-holder">
                    <button type="submit" class="btn-mvc-green btn-mvc-large">@Html.LanguageString("Buttons.Save")</button>
                </div>
            </fieldset>
        }

    </div>
</div>

MVCForum.Website/Views/Members/ForgotPassword.cshtml
@model MVCForum.Website.ViewModels.ForgotPasswordViewModel
@{
    Layout = "~/Views/Shared/_LayoutFullWidth.cshtml";
    ViewBag.Title = Html.LanguageString("Members.ForgotPassword.Title");
}

<div class="row">

    <div class="col-md-6 col-md-offset-3">

        @using (Html.BeginForm("ForgotPassword", "Members", FormMethod.Post, new { @class = "form-forgotpassword" }))
        {

            @Html.ValidationSummary(true)
            @Html.AntiForgeryToken()

            <h3>@ViewBag.Title</h3>

            <div class="form-group">
                @Html.LabelFor(m => m.EmailAddress)
                @Html.TextBoxFor(m => m.EmailAddress, new { @class="form-control", type="email" })
                @Html.ValidationMessageFor(m => m.EmailAddress)
            </div>

            <div class="submit-holder">
                <button type="submit" class="btn-mvc-green btn-mvc-large">@Html.LanguageString("Buttons.ResetPassword")</button>
            </div>

        }

    </div>

</div>

MVCForum.Website/Views/Members/GetMemberDiscussions.cshtml
@using MVCForum.Website.ViewModels
@model ViewMemberDiscussionsViewModel

@foreach (var topic in Model.Topics)
{
    Html.RenderPartial("_TopicSlim", topic);    
}

MVCForum.Website/Views/Members/LatestMembersJoined.cshtml
@model MVCForum.Website.ViewModels.ListLatestMembersViewModel

@if(Model.Users.Any())
{
    <ul class="latestmembersjoined">
    @foreach (var user in Model.Users)
    {
        <li><a href="@Html.Raw(user.Value)">@Html.Raw(user.Key)</a></li>
    }
    </ul>
}

MVCForum.Website/Views/Members/LogOn.cshtml
@using MVCForum.Website.Application.ExtensionMethods
@model MVCForum.Website.ViewModels.LogOnViewModel
@{
    Layout = "~/Views/Shared/_LayoutFullWidth.cshtml";
    ViewBag.Title = Html.LanguageString("LogOn.LogOn");
}

<div class="row">

    <div class="col-md-6 col-md-offset-3">

        @Html.Partial("_SocialLoginButtons")

        @if (Html.Settings().DisableStandardRegistration != true)
        {
            <div class="mainlogonform">

                <h3>@ViewBag.Title</h3>

                @using (Html.BeginForm("LogOn", "Members", FormMethod.Post, new { @class = "form-login" }))
                {
                    @Html.ValidationSummary(false)
                    @Html.AntiForgeryToken()

                    if (Html.Settings().DisableStandardRegistration != true)
                    {
                        <p class="help-block">@Html.Raw(string.Format(Html.LanguageString("Members.LogOnMessage"), Html.ActionLink(Html.Lang("Members.Register"), "Register")))</p>
                    }

                    <div class="form-group">
                        @Html.LabelFor(m => m.UserName)
                        @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.UserName)
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(m => m.Password)
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Password)
                    </div>

                    <div class="checkbox">
                        @using (Html.BeginLabelFor(m => m.RememberMe, new { @class = "checkbox" }))
                    {
                            @Html.CheckBoxFor(m => m.RememberMe)
                        }
                        @Html.ValidationMessageFor(m => m.RememberMe)
                    </div>

                    <div class="submit-holder">
                        <button type="submit" class="btn-mvc-green btn-mvc-large">@Html.LanguageString("Buttons.LogOn")</button>
                    </div>

                    @Html.HiddenFor(x => x.ReturnUrl)
                }
            </div>

            <p class="forgotpasswordtext">
                <a href="@Url.Action("ForgotPassword")">
                    @Html.LanguageString("Members.ForgotPassword.Link")
                </a>
            </p>
        }
    </div>

</div>

MVCForum.Website/Views/Members/PasswordChanged.cshtml
@{
    Layout = "~/Views/Shared/_LayoutFullWidth.cshtml";
    ViewBag.Title = Html.LanguageString("Members.ChangePassword.Success");
}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="mainheading">
            <h1>@ViewBag.Title</h1>
        </div>
        <p>@Html.LanguageString("Members.ResetPassword.SuccessText")</p>
        <p>@Html.ActionLink(Html.Lang("Layout.Nav.Logon"), "LogOn", "Members", null, new { @class = "btn-mvc-green btn-mvc-large" })</p>
    </div>
</div>

MVCForum.Website/Views/Members/PasswordResetSent.cshtml
@{
    Layout = "~/Views/Shared/_LayoutFullWidth.cshtml";
    ViewBag.Title = Html.LanguageString("Members.ResetPassword.Title");
}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="mainheading">
            <h1>@ViewBag.Title</h1>
        </div>
        <p>@Html.LanguageString("Members.ResetPassword.Text")</p>
    </div>
</div>

MVCForum.Website/Views/Members/Report.cshtml
@model MVCForum.Website.ViewModels.ReportMemberViewModel

@{
    Layout = "~/Views/Shared/_LayoutFullWidth.cshtml";
    ViewBag.Title = string.Concat(Html.LanguageString("Report.Report"), " ", Model.Username);
}

<div class="row">

    <div class="col-md-6 col-md-offset-3">
        @using (Html.BeginForm("Report", "Members", FormMethod.Post, new { @class = "form-report" }))
        {
            @Html.HiddenFor(x => Model.Id)
            @Html.ValidationSummary(false)

            <h2>@ViewBag.Title</h2>

            <div class="form-group">
                @Html.LabelFor(model => model.Reason)
                @Html.TextAreaFor(model => model.Reason, new { @class = "form-control textarea" })
                @Html.ValidationMessageFor(model => model.Reason)
            </div>

            <div class="submit-holder">
                <button type="submit" class="btn-mvc-green btn-mvc-large">
                    @Html.LanguageString("Buttons.Send")
                </button>
            </div>
        }
    </div>
</div>

MVCForum.Website/Views/Members/SideAdminPanel.cshtml
@model MVCForum.Website.ViewModels.ViewAdminSidePanelViewModel

@if (Model.IsDropDown)
{
    <li class="dropdown">
        <a href="#" class="dropdown-toggle mytoolslink" data-toggle="dropdown">
            @Html.LanguageString("SideBox.MyTools")
            @if (Model.NewPrivateMessageCount > 0 || Model.ModerateCount > 0)
            {
                if (Model.ModerateCount > 0)
                {
                    <span class="badge">@Model.ModerateCount</span> 
                }
                if (Model.NewPrivateMessageCount > 0)
                {
                    <span class="badge">@Model.NewPrivateMessageCount</span>
                }
            }
            else
            {
                <span class="caret"></span>
            }
        </a>
        <ul class="dropdown-menu" role="menu">
            @Html.Raw(DropDownContents())
        </ul>
    </li>
}
else
{
    @Html.Raw(DropDownContents())
}



@helper DropDownContents()
{
    if (User.IsInRole(AppConstants.AdminRoleName))
    {
        <li><a href="@Url.Action("Index", "Admin", new {area = "Admin"}, null)">@Html.LanguageString("Layout.Nav.Admin")</a></li>
    }
    <li>@Html.ActionLink(Html.LanguageString("Members.SearchMembers"), "Search", "Members")</li>
    <li>
        <a href="@Url.Action("Edit", "Members", new { id = Model.CurrentUser.Id })">@Html.LanguageString("Buttons.Edit") @Model.CurrentUser.UserName</a>
    </li>
    if (Model.CanViewPrivateMessages)
    {
        <li>
            <a href="@Url.Action("Index", "PrivateMessage")">
                @Html.LanguageString("PM.PrivateMessages")
                @if (Model.NewPrivateMessageCount > 0)
                {
                    <span class="badge">@Model.NewPrivateMessageCount</span>
                }
            </a>
        </li>
}
    if (Model.ModerateCount > 0)
    {
        <li>
            <a href="@Url.Action("Index", "Moderate")" class="moderatepanelnav" data-name="@Html.Lang("Moderate.NavText")">
                @Html.LanguageString("Moderate.NavText")
                @if (Model.ModerateCount > 0)
                {
                    <span class="badge">@Model.ModerateCount</span>
                }
            </a>
        </li>
    }

    <li>@Html.ActionLink(Html.LanguageString("LogOn.LogOff"), "LogOff", "Members")</li>
}