MVCForum.Website/Areas/Admin/ViewModels/AdminTagViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using MVCForum.Domain.DomainModel;

namespace MVCForum.Website.Areas.Admin.ViewModels
{
    public class MoveTagsViewModel
    {
        [Required]
        [DisplayName("Current Tag")]
        public Guid CurrentTagId { get; set; }
        [Required]
        [DisplayName("Tag where everything is going")]
        public Guid NewTagId { get; set; }
        public List<SelectListItem> Tags { get; set; }
    }

    public class ListTagsViewModel
    {
        public PagedList<TopicTag> Tags { get; set; }
        public int? PageIndex { get; set; }
        public int? TotalCount { get; set; }
        public string Search { get; set; }
    }

    public class AjaxEditTagViewModel
    {
        [Required]
        public string OldName { get; set; }

        [Required]
        public string NewName { get; set; }
    }
}

MVCForum.Website/Areas/Admin/Controllers/AdminTagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using MVCForum.Domain.Constants;
using MVCForum.Domain.DomainModel;
using MVCForum.Domain.Interfaces.Services;
using MVCForum.Domain.Interfaces.UnitOfWork;
using MVCForum.Website.Areas.Admin.ViewModels;

namespace MVCForum.Website.Areas.Admin.Controllers
{
    [Authorize(Roles = AppConstants.AdminRoleName)]
    public partial class AdminTagController : BaseAdminController
    {
        private readonly ITopicTagService _topicTagService;

        public AdminTagController(ILoggingService loggingService, IUnitOfWorkManager unitOfWorkManager, IMembershipService membershipService, 
            ILocalizationService localizationService, ISettingsService settingsService, ITopicTagService topicTagService) 
            : base(loggingService, unitOfWorkManager, membershipService, localizationService, settingsService)
        {
            _topicTagService = topicTagService;
        }

        public ActionResult Index(int? p, string search)
        {
            var pageIndex = p ?? 1;

            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var allTags = string.IsNullOrEmpty(search) ? _topicTagService.GetPagedGroupedTags(pageIndex, SiteConstants.Instance.AdminListPageSize) :
                            _topicTagService.SearchPagedGroupedTags(search, pageIndex, SiteConstants.Instance.AdminListPageSize);

                var memberListModel = new ListTagsViewModel
                {
                    Tags = allTags,
                    PageIndex = pageIndex,
                    TotalCount = allTags.TotalCount,
                    Search = search
                };

                return View(memberListModel);
            }

        }

        private List<SelectListItem> TagsSelectList()
        {
            var list = new List<SelectListItem>();
            foreach (var tag in _topicTagService.GetAll().OrderBy(x => x.Tag).ToList())
            {
                list.Add(new SelectListItem
                {
                    Text = tag.Tag,
                    Value = tag.Id.ToString()
                });
            }
            return list;
        }

        public ActionResult MoveTags()
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var viewModel = new MoveTagsViewModel
                                {
                                    Tags = TagsSelectList()
                                };
                return View(viewModel);
            }
        }

        [HttpPost]
        public ActionResult MoveTags(MoveTagsViewModel viewModel)
        {
            using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
            {
                var oldTag = _topicTagService.Get(viewModel.CurrentTagId);
                var newTag = _topicTagService.Get(viewModel.NewTagId);

                // Look through the topics and add the new tag to it and remove the old!                
                var topics = new List<Topic>();
                topics.AddRange(oldTag.Topics);
                foreach (var topic in topics)
                {
                    topic.Tags.Remove(oldTag);
                    topic.Tags.Add(newTag);
                }

                // Reset the tags
                viewModel.Tags = TagsSelectList();

                try
                {
                    unitOfWork.Commit();
                    ShowMessage(new GenericMessageViewModel
                    {
                        Message = $"All topics tagged with {oldTag.Tag} have been updated to {newTag.Tag}",
                        MessageType = GenericMessages.success
                    });
                }
                catch (Exception ex)
                {
                    unitOfWork.Rollback();
                    LoggingService.Error(ex);
                    ShowMessage(new GenericMessageViewModel
                    {
                        Message = $"Error: {ex.Message}",
                        MessageType = GenericMessages.danger
                    });
                }

                return View(viewModel); 
            }
        }


        public ActionResult Manage(int? p, string search)
        {
            return RedirectToAction("Index", new { p, search });
        }


        public ActionResult Delete(string tag)
        {


            using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
            {
                _topicTagService.DeleteByName(tag);

                TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                {
                    Message = "Tags delete successfully",
                    MessageType = GenericMessages.success
                };

                try
                {
                    unitOfWork.Commit();
                }
                catch (Exception ex)
                {
                    unitOfWork.Rollback();
                    LoggingService.Error(ex);
                    ShowMessage(new GenericMessageViewModel
                    {
                        Message = $"Delete failed: {ex.Message}",
                        MessageType = GenericMessages.danger
                    });
                }

            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public void UpdateTag(AjaxEditTagViewModel viewModel)
        {
            if (Request.IsAjaxRequest())
            {
                using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
                {
                    _topicTagService.UpdateTagNames(viewModel.NewName, viewModel.OldName);

                    try
                    {
                        unitOfWork.Commit();
                    }
                    catch (Exception ex)
                    {
                        unitOfWork.Rollback();
                        LoggingService.Error(ex);
                    }
                }
            }
        }


    }
}

MVCForum.Website/Areas/Admin/Views/AdminTag/Index.cshtml
@using MVCForum.Domain.Constants
@model MVCForum.Website.Areas.Admin.ViewModels.ListTagsViewModel

@{
    ViewBag.Title = "Manage Tags";
}

<div class="panel">
    <div class="panel-heading">
        <h5>@ViewBag.Title</h5>
    </div>
    <div class="panel-content">
        @using (Html.BeginForm("Manage", "AdminTag", FormMethod.Post))
        {
            @Html.HiddenFor(x => x.PageIndex)
            <div class="input-group tablesearch">
                @Html.TextBoxFor(x => Model.Search, new { @class = "form-control" })
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">Search</button>
                </span>
            </div>
        }

        @if (Model.TotalCount > 0)
        {
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th style="width: 65px;">Edit</th>
                        <th>Tag</th>
                        <th style="width: 65px;">Delete</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var tag in Model.Tags)
                    {
                        <tr>
                            <td class="tagcell">
                                <span class="edittag">
                                    <a href="#" class="btn-mvc">
                                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                    </a>
                                </span>
                                <span class="savetag" style="display:none;">
                                    <a href="#" class="btn-mvc">
                                        <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                                    </a>
                                </span>
                            </td>
                            <td class="tagvalue">
                                <strong>

                                    <span class="tagvaluedisplay">
                                        @tag.Tag
                                    </span>
                                    <span class="tagvalueedit" style="display:none;">
                                        <input data-tagid="@tag.Id" data-oldvalue="@tag.Tag" type="text" id="@tag.Id" value="@tag.Tag" class="taginput form-control" />
                                    </span>

                                </strong>
                            </td>
                            <td>
                                <a href="@Url.Action("Delete", new { tag = tag.Tag })" class="btn-mvc">
                                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>

            if (Model.Tags.TotalPages > 1)
            {
                @Html.Pager(Convert.ToInt32(Model.PageIndex), SiteConstants.Instance.AdminListPageSize, Convert.ToInt32(Model.TotalCount), new { search = Model.Search })
            }
        }
    </div>
</div>

MVCForum.Website/Areas/Admin/Views/AdminTag/MoveTags.cshtml
@model MVCForum.Website.Areas.Admin.ViewModels.MoveTagsViewModel
@{
    ViewBag.Title = "Change Tags";
}

<div class="panel">
    <div class="panel-heading">
        <h4 class="panel-title">
            @ViewBag.Title
        </h4>
    </div>
    <div class="panel-body">
        <p>This page enables you to move topics from one tag to another, perfect if you want to delete a tag.</p>

        @using (Html.BeginForm("MoveTags", "AdminTag", FormMethod.Post))
        {
            @Html.ValidationSummary(false)

            <div class="form-group">
                @Html.LabelFor(m => m.CurrentTagId)
                @Html.DropDownListFor(m => m.CurrentTagId, Model.Tags, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.CurrentTagId)
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.NewTagId)
                @Html.DropDownListFor(m => m.NewTagId, Model.Tags, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.NewTagId)
            </div>

            <div class="submit-holder">
                <input type="submit" class="btn-mvc-green btn-mvc-large" value="Update" />
            </div>
        }

    </div>
</div>